language: python
python:
  - "3.6"
  
services:
  - docker
  
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
    # Testing the installation of the ghdl
  - docker run -t ghdl/ghdl:stretch-mcode ghdl --version
    # Mount the repo to docker, and run the hello word example.
  - docker run -t -v `pwd`:/mnt/data ghdl/ghdl:stretch-mcode  /bin/bash -c  "chmod u+w /mnt/data/compile.sh; /mnt/data/compile.sh"
    # Mount the repo to docker, and run the hello word script.
  - docker run -t -v `pwd`:/mnt/data ghdl/ghdl:stretch-mcode  /bin/bash -c "chmod u+w /mnt/data/*.sh; /mnt/data/addre.sh"

notifications:
  email:
    on_success: never
    on_failure: always
