dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  
services:
  - docker
  
# command to install dependencies
install:
  - pip install -r requirements.txt

before_install:
- docker run -t ghdl/ghdl:stretch-mcode ghdl --version
- docker run -t -v `pwd`/test:/mnt/data ghdl/ghdl:stretch-mcode ls -al
- docker run -t -v `pwd`/test:/mnt/data ghdl/ghdl:stretch-mcode ls /mnt/data
- docker run -t -v `pwd`/test:/mnt/data ghdl/ghdl:stretch-mcode ghdl -a /mnt/data/hw.vhd
- docker run -t -v `pwd`/test:/mnt/data ghdl/ghdl:stretch-mcode ghdl -e hello_world
- docker run -t -v `pwd`/test:/mnt/data ghdl/ghdl:stretch-mcode ghdl -r hello_world
  
# command to run tests
script:
  - pytest --cov=cct
  
# Push the results back to codecov
after_success:
- codecov  

notifications:
  email:
    on_success: never
    on_failure: always
